swagger: '2.0'
info:
  title: api-jwt
  x-ibm-name: api-jwt
  version: 1.0.0
x-ibm-configuration:
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - operation-switch:
          version: 2.0.0
          title: operation-switch
          case:
            - operations:
                - verb: get
                  path: /gen
              execute:
                - set-variable:
                    version: 2.0.0
                    title: set-variable
                    actions:
                      - set: hs256-key
                        value: >-
                          { "alg": "HS256", "kty": "oct", "use": "sig", "k":
                          "o5yErLaE-dbgVpSw65Rq57OA9dHyaF66Q_Et5azPa-XUjbyP0w9iRWhR4kru09aFfQLXeIODIN4uhjElYKXt8n76jt0Pjkd2pqk4t9abRF6tnL19GV4pflfL6uvVKkP4weOh39tqHt4TmkBgF2P-gFhgssZpjwq6l82fz3dUhQ2nkzoLA_CnyDGLZLd7SZ1yv73uzfE2Ot813zmig8KTMEMWVcWSDvy61F06vs_6LURcq_IEEevUiubBxG5S2akNnWigfpbhWYjMI5M22FOCpdcDBt4L7K1-yHt95Siz0QUb0MNlT_X8F76wH7_A37GpKKJGqeaiNWmHkgWdE8QWDQ",
                          "kid": "hs256-key" }
                        type: string
                    description: set
                - gatewayscript:
                    version: 2.0.0
                    title: gatewayscript
                    source: "var apim = require('apim');\r\n\r\nvar json_privateclaim = {\r\n\t'bank': {\r\n\t\t'code':'200',\r\n\t\t'description':'ok',\r\n\t\t'server_code':'0',\r\n\t\t'server_description':'Success',\r\n\t\t'data':{\r\n\t\t\t'client_id':'123456789',\r\n\t\t\t'client_type':'1'\r\n\t\t}\r\n\t}\t\r\n};\r\napim.setvariable('private.claim', json_privateclaim);"
                - jwt-generate:
                    version: 2.0.0
                    title: jwt-generate
                    jwt: generated.jwt
                    iss-claim: request.headers.iss-claim
                    exp-claim: 60
                    aud-claim: request.headers.aud-claim
                    jws-jwk: hs256-key
                    jws-alg: HS256
                    sub-claim: request.headers.subject-claim
                    private-claims: private.claim
                - gatewayscript:
                    version: 2.0.0
                    title: gatewayscript
                    source: "var apim = require('apim');\r\nvar json_output = {\r\n\t'jwt': apim.getvariable('generated.jwt')\r\n};\r\n\r\napim.output('application/json');\r\nsession.output.write(json_output);"
            - operations:
                - verb: get
                  path: /val
              execute:
                - set-variable:
                    version: 2.0.0
                    title: set-variable
                    actions:
                      - set: hs256-key
                        value: >-
                          { "alg": "HS256", "kty": "oct", "use": "sig", "k":
                          "o5yErLaE-dbgVpSw65Rq57OA9dHyaF66Q_Et5azPa-XUjbyP0w9iRWhR4kru09aFfQLXeIODIN4uhjElYKXt8n76jt0Pjkd2pqk4t9abRF6tnL19GV4pflfL6uvVKkP4weOh39tqHt4TmkBgF2P-gFhgssZpjwq6l82fz3dUhQ2nkzoLA_CnyDGLZLd7SZ1yv73uzfE2Ot813zmig8KTMEMWVcWSDvy61F06vs_6LURcq_IEEevUiubBxG5S2akNnWigfpbhWYjMI5M22FOCpdcDBt4L7K1-yHt95Siz0QUb0MNlT_X8F76wH7_A37GpKKJGqeaiNWmHkgWdE8QWDQ",
                          "kid": "hs256-key" }
                        type: string
                    description: set
                - jwt-validate:
                    version: 2.0.0
                    title: jwt-validate
                    jwt: request.headers.authorization
                    output-claims: decoded.claims
                    jws-jwk: hs256-key
                - gatewayscript:
                    version: 2.0.0
                    title: gatewayscript
                    source: "var apim = require('apim');\r\nvar json_output = apim.getvariable('decoded.claims');\r\n\r\napim.output('application/json');\r\nsession.output.write(json_output);"
          otherwise: []
    catch:
      - default:
          - gatewayscript:
              version: 2.0.0
              title: gatewayscript
              source: "var apim = require('apim');\r\nvar json_output = {\r\n\t'code': '404',\r\n\t'message': 'Token\_no\_existe\_en\_cache',\r\n\t'msg': apim.getvariable('jwt-validate.error-message')\r\n};\r\n\r\napim.output('application/json');\r\nsession.output.write(json_output);"
  properties:
    target-url:
      value: http://example.com/operation-name
      description: The URL of the target service
      encoded: false
  activity-log:
    enabled: true
    success-content: activity
    error-content: payload
basePath: /api-jwt
paths:
  /gen:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
    parameters:
      - name: iss-claim
        required: true
        in: header
        type: string
        description: Enter https://myidp.ibm.com
      - name: aud-claim
        required: true
        in: header
        type: string
        description: Enter ClientID1
  /val:
    get:
      responses:
        '200':
          description: success
          schema:
            type: string
    parameters:
      - name: Authorization
        required: true
        in: header
        type: string
        description: Enter Bearer <jwt>
securityDefinitions:
  clientID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
security:
  - clientID: []
schemes:
  - https
